### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by blueclouds8666** [ykhwong/dummy-dll-generator#2]
when i try to dummy a dll file, the following error happens:

```
C:\patcher>dummyDLL.exe library.dll

Dummy DLL Generator v0.1 (20190627a)

Error: Could not ReadDir

C:\patcher>dummyDLL.exe C:\patcher\library.dll

Dummy DLL Generator v0.1 (20190627a)

Error: Could not ReadDir
```
despite library.dll being present in that same folder (it only contains dummyDLL.exe and library.dll)
i have visual C++ 2017 redistributable installed, as well as visual studio 2017. i'm using the [20190627a](https://github.com/ykhwong/dummy-dll-generator/releases/tag/20190627) release

**Comment by ykhwong** [comment]
The error message means that the \VC\Tools\MSVC directory is missing. Please install Microsoft Visual C++ Build tools in the Visual Studio Installer.

**Comment by naqaden** [comment]
For others running into this, installing MSVC was not enough. I then got this error:
`LINK : fatal error LNK1181: cannot open input file 'kernel32.lib'`
and solved that by installing Windows SDK.

**Comment by brian6932** [comment]
@naqaden Which Windows SDK did you install? I have 10.0.22621.0 and am encountering it.

**Comment by naqaden** [comment]
@brian6932 Since I'm still running 10 I chose an old Win 10 SDK (10.0.18362.0) from VS Installer.
